name: ShiftLeft Best Fix Analysis 
on:
  pull_request:
  workflow_dispatch:
env:
  AppName: Illingworth-PatientGo_dotNET
jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: bestfix.py
      run: |
        cd /home/runner/work/field-integrations/field-integrations/shiftleft-utils
        pip install --upgrade pip
        pip install -r requirements.txt        
        py /bestfix.py -a $AppName 
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
